---
abstract: 'a superdaemon for hot-deploying server programs'
author:
  - 'Kazuho Oku <kazuhooku@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::TCP: 0.11
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Server-Starter
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 0
  Proc::Wait3: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
