---
abstract: 'a superdaemon for hot-deploying server programs'
author:
  - 'Kazuho Oku'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Server-Starter
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 0
  List::MoreUtils: 0
  Proc::Wait3: 0
  Scope::Guard: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.19'
